apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: your-django-image:latest
        imagePullPolicy: Never   # <-- Important for Minikube local builds
        command: ["gunicorn"]
        args: ["ecommerce.wsgi:application", "--bind", "0.0.0.0:8000"]  # Change 'ecommerce' to your project folder name
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "ecommerce.settings"  # Change 'ecommerce' here too
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres:5432/postgres"
